title: The Binary Times
email: info@thebinarytimes.net
description: >- # this means to ignore newlines until "baseurl:"
    GNU/Linux tips and tricks, everyday GNU/Linux IT usage and news.  Make the most of your GNU/Linux installation
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://192.168.1.100:4000" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: thebinarytimes
#github_username:  thebinarytimes

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
